apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" .Values.sample.label }} 
spec:
  selector:
    app: {{ .Values.sample.label }}
  ports:
    - port: {{ .Values.sample.service.port }}
      targetPort: {{ .Values.sample.containerPort }}
  type: {{ .Values.sample.service.type }}
